version: '2'

services:
  addok%N:
    image: etalab/addok
    container_name: addok%N
    volumes:
      - ./addok-data/addok.conf:/etc/addok/addok.conf
      - ./addok-data/addok.db:/data/addok.db
      - ./logs:/logs
    links:
      - addok-redis%N:redis
    environment:
      WORKERS: ${WORKERS}
      LOG_QUERIES: 1
      LOG_NOT_FOUND: 1
      SLOW_QUERIES: 200
  addok-redis%N:
    image: etalab/addok-redis
    container_name: redis%N
    volumes:
      - ./addok-data/dump.rdb:/data/dump.rdb

